.PHONY: clean All

All:
	@echo "----------构建项目：[demo2 - Debug ]----------"
	@cd "demo2" && $(MAKE) -f  "demo2.mk"
clean:
	@echo "----------清理项目：[demo2 - Debug ]----------"
	@cd "demo2" && $(MAKE) -f  "demo2.mk" clean
